### PR TITLE
Replaced try/finally with try-with-resources

### PR DESCRIPTION
**Pull request by barthanssens**
This PR addresses GitHub issue: #23  .

Briefly describe the changes proposed in this PR:

* Replaced try/finally blocks on autocloseables with try-with-resources

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
@barthanssens there's some conflicts on this PR (possibly due to the fact that we left it open too long, apologies). Can you rebase with the develop branch and resolve the conflicts?

**Comment by barthanssens** [comment]
Ok, thanks, I'll rebase the changes (probably my own restructuring in another PR is too blame :-)

**Comment by jeenbroekstra** [comment]
@barthanssens I managed to fix line ending issues in several of your PRs. I'll leave this one open for you, so you can quickly test your local settings and fix where necessary. 

One thing you should definitely do is run `git add --renormalize .` on your local repo, commit, and push. I'm not sure if you need to run this on each indivual branch or not, but to be safe maybe best to do this on both master and develop, at least. See https://stackoverflow.com/questions/7156694/git-how-to-renormalize-line-endings-in-all-files-in-all-revisions/47580886#47580886 . Hopefully the problem is simply that your clone's index is out of date, and this will fix the problem.

**Comment by barthanssens** [comment]
Hi @jeenbroekstra ,
thanks for the link, I think it worked, sorry for the extra work

**Comment by jeenbroekstra** [comment]
@barthanssens no worries, glad it got fixed :)

**Pull request closed without merging**
