### PR TITLE
Fix #11 Add web support for repositories with Lucene

### LINKED ISSUE #11: Add web support for LuceneSpinSail
It requires several changes in rdf4j-storage:

- [x] adapt package `rdf4j-lucene-spin`  ref. PR eclipse/rdf4j-storage#31
- [x] create *.ttl layout in `rdf4j-repository-api`ref PR eclipse/rdf4j#965
- [x] add menu layout files  ref PR #14

### PR DESCRIPTION
**Pull request by jgrzebyta**
This PR addresses GitHub issue: #11  .
This PR brings together all other PRs required by this issue.

Briefly describe the changes proposed in this PR:

* add menu options for "In Memory Store with RDFS+SPIN+Lucene support".

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
Looks good. Could we also add an option with only Memory + Lucene  / Native + Lucene (so no SPIN, no RDFS)?

**Comment by jgrzebyta** [comment]
Ok I will do that. However the syntax will be different. It is because SPIN
implementation bases on magic property syntax.

**Comment by jgrzebyta** [comment]
Done.

@jamesrdf This PR is related to https://github.com/eclipse/rdf4j/pull/965
so please could you change milestone for both PRs into 2.3.1.

**Comment by jgrzebyta** [comment]
For some reason the lucene index location is `<reponame>.index` even is SYSTEM shows different one.
It seems it takes default location.

**Comment by jgrzebyta** [comment]
Relocate as unit test in `rdf4j-sail-lucene`.

**Comment by jgrzebyta** [comment]
Sorry, wrong PR was closed tonight. This PR is still to merge.

**Pull request merged**
